const fs = require('fs');
const outPath = 'E:\\星寰海\\.board\\index.html';
const ws = fs.createWriteStream(outPath, { encoding: 'utf8' });

function w(s) { ws.write(s); }

w('<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>项目看板 - 星寰海</title>\n<style>\n');
w(':root{--bg:#0f172a;--bg-card:#1e293b;--bg-card-hover:#334155;--text:#e2e8f0;--text-dim:#94a3b8;--text-muted:#64748b;--accent:#38bdf8;--accent2:#818cf8;--green:#4ade80;--green-bg:rgba(74,222,128,0.1);--yellow:#fbbf24;--yellow-bg:rgba(251,191,36,0.1);--red:#f87171;--red-bg:rgba(248,113,113,0.1);--blue:#60a5fa;--blue-bg:rgba(96,165,250,0.1);--pink:#f472b6;--pink-bg:rgba(244,114,182,0.1);--purple:#a78bfa;--purple-bg:rgba(167,139,250,0.1);--border:#334155;--radius:10px}\n');
w('*{margin:0;padding:0;box-sizing:border-box}\nbody{font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,\'Noto Sans SC\',sans-serif;background:var(--bg);color:var(--text);line-height:1.6}\n');
w('::-webkit-scrollbar{width:6px;height:6px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:var(--border);border-radius:3px}::-webkit-scrollbar-thumb:hover{background:var(--text-muted)}\n');
w('.layout{display:flex;min-height:100vh}\n.sidebar{width:240px;background:#0c1222;border-right:1px solid var(--border);flex-shrink:0;display:flex;flex-direction:column;position:sticky;top:0;height:100vh;overflow-y:auto}\n');
w('.sidebar-top{padding:20px 16px 16px;border-bottom:1px solid var(--border)}.sidebar-project{display:flex;align-items:center;gap:10px;font-size:16px;font-weight:700}\n');
w('.sidebar-pulse{width:10px;height:10px;border-radius:50%;background:var(--green);position:relative;flex-shrink:0}.sidebar-pulse::after{content:\'\';position:absolute;inset:-3px;border-radius:50%;border:2px solid var(--green);animation:pulse 2s ease-out infinite;opacity:0}\n');
w('@keyframes pulse{0%{transform:scale(0.8);opacity:0.8}100%{transform:scale(2);opacity:0}}\n');
w('.sidebar-section{margin-top:4px}.sidebar-label{padding:10px 16px 6px;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;color:var(--text-muted);font-weight:600}\n');
w('.sidebar-item{padding:8px 16px 8px 28px;font-size:13px;cursor:pointer;color:var(--text-dim);transition:all 0.15s;border-left:3px solid transparent;display:flex;align-items:center;gap:8px}\n');
w('.sidebar-item:hover{background:rgba(255,255,255,0.04);color:var(--text)}.sidebar-item.active{background:rgba(56,189,248,0.08);color:var(--accent);border-left-color:var(--accent)}\n');
w('.sidebar-item .icon{font-size:14px;width:18px;text-align:center}\n');
w('.sidebar-date{padding:5px 16px 5px 28px;font-size:12px;cursor:pointer;color:var(--text-muted);transition:all 0.15s;display:flex;justify-content:space-between;align-items:center}\n');
w('.sidebar-date:hover{color:var(--text-dim);background:rgba(255,255,255,0.03)}.sidebar-date.active{color:var(--accent)}\n');
w('.sidebar-date .count{font-size:10px;background:var(--border);padding:1px 6px;border-radius:8px;color:var(--text-dim)}\n');
w('.sidebar-bottom{margin-top:auto;padding:12px 16px;border-top:1px solid var(--border)}.ws-status{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--text-muted)}\n');
w('.ws-dot{width:8px;height:8px;border-radius:50%;background:var(--red);flex-shrink:0;transition:background 0.3s}.ws-dot.connected{background:var(--green)}\n');
w('.main{flex:1;padding:24px 32px;max-width:960px;min-width:0}\n');
w('.header{background:linear-gradient(135deg,#1e293b 0%,#0f172a 100%);border:1px solid var(--border);border-radius:var(--radius);padding:24px 28px;margin-bottom:24px}\n');
w('.header-top{display:flex;align-items:baseline;gap:12px;margin-bottom:4px;flex-wrap:wrap}.header h1{font-size:22px;font-weight:700}\n');
w(':700}.header-stage{font-size:13px;color:var(--accent);background:rgba(56,189,248,0.1);padding:2px 10px;border-radius:12px}\n');
w('.header-branch{font-size:13px;color:var(--purple);background:var(--purple-bg);padding:2px 10px;border-radius:12px}\n');
w('.header-meta{font-size:13px;color:var(--text-dim);margin-top:4px;display:flex;gap:16px;flex-wrap:wrap}.header-meta span{display:flex;align-items:center;gap:4px}\n');
w('.progress-wrap{margin-top:16px}.progress-label{display:flex;justify-content:space-between;font-size:12px;color:var(--text-dim);margin-bottom:6px}\n');
w('.progress-bar{height:8px;background:var(--border);border-radius:4px;overflow:hidden}.progress-fill{height:100%;background:linear-gradient(90deg,var(--accent),var(--green));border-radius:4px;transition:width 0.6s ease}\n');
w('.view{display:none}.view.active{display:block}\n');
w('.stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:24px}\n');
w('.stat-card{background:var(--bg-card);border:1px solid var(--border);border-radius:var(--radius);padding:16px 18px;transition:border-color 0.15s}.stat-card:hover{border-color:var(--text-muted)}\n');
w('.stat-card .stat-num{font-size:28px;font-weight:700}.stat-card .stat-label{font-size:12px;color:var(--text-dim);margin-top:2px}\n');
w('.stat-card.green .stat-num{color:var(--green)}.stat-card.yellow .stat-num{color:var(--yellow)}.stat-card.blue .stat-num{color:var(--blue)}.stat-card.red .stat-num{color:var(--red)}\n');
w('.stat-card.green{border-left:3px solid var(--green)}.stat-card.yellow{border-left:3px solid var(--yellow)}.stat-card.blue{border-left:3px solid var(--blue)}.stat-card.red{border-left:3px solid var(--red)}\n');
w('.section-title{font-size:16px;font-weight:600;margin-bottom:14px;display:flex;align-items:center;gap:8px}\n');
w('.module-list{display:flex;flex-direction:column;gap:8px}\n');
w('.module-row{display:flex;align-items:center;gap:12px;padding:10px 14px;background:var(--bg-card);border:1px solid var(--border);border-radius:8px;transition:background 0.15s}.module-row:hover{background:var(--bg-card-hover)}\n');
w('.module-row .m-name{font-size:13px;font-weight:600;min-width:80px}.module-row .m-desc{font-size:12px;color:var(--text-dim);flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n');
w('.module-row .m-bar{width:100px;height:6px;background:var(--border);border-radius:3px;overflow:hidden;flex-shrink:0}.module-row .m-bar-fill{height:100%;border-radius:3px;transition:width 0.4s}\n');
w('.module-row .m-pct{font-size:12px;color:var(--text-dim);min-width:36px;text-align:right}\n');
w('.badge{display:inline-block;padding:2px 10px;border-radius:12px;font-size:11px;font-weight:600;white-space:nowrap}\n');
w('.badge-done{background:var(--green-bg);color:var(--green)}.badge-doing{background:var(--yellow-bg);color:var(--yellow)}.badge-pending{background:var(--blue-bg);color:var(--blue)}.badge-blocked{background:var(--red-bg);color:var(--red)}\n');
w('.badge-change{background:var(--blue-bg);color:var(--blue)}.badge-done-tl{background:var(--green-bg);color:var(--green)}.badge-fail{background:var(--red-bg);color:var(--red)}.badge-review{background:var(--yellow-bg);color:var(--yellow)}\n');
w('.badge-sync{background:var(--purple-bg);color:var(--purple)}.badge-test{background:var(--pink-bg);color:var(--pink)}\n');
w('.filter-bar{display:flex;gap:8px;margin-bottom:16px;flex-wrap:wrap}\n');
w('.filter-btn{padding:5px 14px;border-radius:16px;font-size:12px;cursor:pointer;border:1px solid var(--border);background:transparent;color:var(--text-dim);transition:all 0.15s}\n');
w('.filter-btn:hover{border-color:var(--text-muted);color:var(--text)}.filter-btn.active{background:rgba(56,189,248,0.12);border-color:var(--accent);color:var(--accent)}\n');
w('.module-card{background:var(--bg-card);border:1px solid var(--border);border-radius:var(--radius);margin-bottom:10px;overflow:hidden;transition:border-color 0.15s}.module-card:hover{border-color:var(--text-muted)}\n');
w('.module-card-header{padding:14px 18px;cursor:pointer;display:flex;align-items:center;gap:12px}\n');
w('.module-card-header .mc-name{font-size:14px;font-weight:600;flex:1}.module-card-header .mc-desc{font-size:12px;color:var(--text-dim);flex:2;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n');
w('.module-card-header .mc-bar{width:120px;height:6px;background:var(--border);border-radius:3px;overflow:hidden}.module-card-header .mc-bar-fill{height:100%;border-radius:3px;transition:width 0.4s}\n');
w('.module-card-header .mc-pct{font-size:13px;color:var(--text-dim);min-width:36px;text-align:right}.module-card-header .mc-arrow{font-size:12px;color:var(--text-muted);transition:transform 0.2s}\n');
w('.module-card.expanded .mc-arrow{transform:rotate(90deg)}\n');
w('.module-card-body{max-height:0;overflow:hidden;transition:max-height 0.3s ease}.module-card.expanded .module-card-body{max-height:500px;border-top:1px solid var(--border)}\n');
w('.module-card-body-inner{padding:12px 18px}\n');
w('.subtask{display:flex;align-items:center;gap:10px;padding:6px 0;font-size:13px}\n');
w('.subtask .st-icon{width:18px;height:18px;border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:11px;flex-shrink:0}\n');
w('.subtask .st-icon.done{background:var(--green-bg);color:var(--green)}.subtask .st-icon.doing{background:var(--yellow-bg);color:var(--yellow)}.subtask .st-icon.pending{background:rgba(100,116,139,0.15);color:var(--text-muted)}\n');
w('.subtask .st-name{color:var(--text-dim)}.subtask .st-name.done{color:var(--text-muted);text-decoration:line-through}\n');
w('.search-box{width:100%;padding:9px 14px 9px 36px;background:var(--bg-card);border:1px solid var(--border);border-radius:8px;color:var(--text);font-size:13px;outline:none;transition:border-color 0.15s}.search-box:focus{border-color:var(--accent)}\n');
w('.search-wrap{position:relative;margin-bottom:14px}.search-wrap .search-icon{position:absolute;left:12px;top:50%;transform:translateY(-50%);color:var(--text-muted);font-size:14px}\n');
w('.date-group{margin-bottom:20px}\n');
w('.date-header{position:sticky;top:0;z-index:10;background:var(--bg);padding:10px 0 8px;font-size:14px;font-weight:600;color:var(--text-dim);border-bottom:1px solid var(--border);margin-bottom:8px;display:flex;align-items:center;gap:8px}\n');
w('.date-header .date-count{font-size:11px;color:var(--text-muted);font-weight:400}\n');
w('.tl-item{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid rgba(51,65,85,0.5)}.tl-item:last-child{border-bottom:none}\n');
w('.tl-dot-col{display:flex;flex-direction:column;align-items:center;padding-top:4px}.tl-dot{width:10px;height:10px;border-radius:50%;flex-shrink:0}\n');
w('.tl-dot.change{background:var(--blue);box-shadow:0 0 6px rgba(96,165,250,0.4)}.tl-dot.done{background:var(--green);box-shadow:0 0 6px rgba(74,222,128,0.4)}\n');
w('.tl-dot.fail{background:var(--red);box-shadow:0 0 6px rgba(248,113,113,0.4)}.tl-dot.review{background:var(--yellow);box-shadow:0 0 6px rgba(251,191,36,0.4)}\n');
w('.tl-dot.sync{background:var(--purple);box-shadow:0 0 6px rgba(167,139,250,0.4)}.tl-dot.test{background:var(--pink);box-shadow:0 0 6px rgba(244,114,182,0.4)}\n');
w('.tl-content{flex:1;min-width:0}.tl-time{font-size:11px;color:var(--text-muted)}\n');
w('.tl-title-row{display:flex;align-items:center;gap:8px;margin:2px 0;flex-wrap:wrap}.tl-title{font-size:14px;font-weight:500}\n');
w('.tl-desc{font-size:13px;color:var(--text-dim);margin-top:2px}.tl-files{font-size:12px;color:var(--accent);font-family:\'SFMono-Regular\',Consolas,monospace;margin-top:4px;word-break:break-all}\n');
w('.tl-actions{margin-top:6px}.tl-view-diff{font-size:12px;color:var(--accent);cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;gap:4px;transition:color 0.15s}.tl-view-diff:hover{color:var(--accent2);text-decoration:underline}\n');
w('.review-card{background:var(--bg-card);border:1px solid var(--border);border-radius:var(--radius);padding:16px 18px;margin-bottom:10px;transition:border-color 0.15s}.review-card:hover{border-color:var(--text-muted)}\n');
w('.review-card.pass{border-left:3px solid var(--green)}.review-card.fail{border-left:3px solid var(--red)}\n');
w('.review-card .rv-icon{font-size:16px;margin-right:6px}.review-card .rv-title{font-size:14px;font-weight:600;display:inline}\n');
w('.review-card .rv-detail{font-size:13px;color:var(--text-dim);margin-top:6px;line-height:1.7}.review-card .rv-meta{font-size:12px;color:var(--text-muted);margin-top:6px;display:flex;gap:16px}\n');
w('.test-header{font-size:13px;color:var(--text-dim);margin-bottom:14px;padding:10px 14px;background:var(--bg-card);border:1px solid var(--border);border-radius:8px}\n');
w('.test-item{display:flex;align-items:center;gap:10px;padding:10px 14px;background:var(--bg-card);border:1px solid var(--border);border-radius:8px;margin-bottom:8px;transition:border-color 0.15s}.test-item:hover{border-color:var(--text-muted)}\n');
w('.test-item .ti-icon{font-size:16px}.test-item .ti-name{font-size:13px;font-weight:500;flex:1}.test-item .ti-result{font-size:12px;color:var(--text-dim)}.test-item .ti-date{font-size:12px;color:var(--text-muted)}\n');
w('.decision-item{padding:12px 16px;background:var(--bg-card);border:1px solid var(--border);border-radius:8px;margin-bottom:8px;transition:border-color 0.15s}.decision-item:hover{border-color:var(--text-muted)}\n');
w('.decision-item .di-title{font-size:14px;font-weight:600}.decision-item .di-title::before{content:\'\\2192 \';color:var(--accent)}\n');
w('.decision-item .di-detail{font-size:13px;color:var(--text-dim);margin-top:4px;line-height:1.7}.decision-item .di-date{font-size:12px;color:var(--text-muted);margin-top:6px}\n');
w('.empty-state{text-align:center;padding:40px;color:var(--text-muted);font-size:14px}\n');
w('.diff-modal-overlay{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.7);z-index:1000;display:flex;align-items:center;justify-content:center;opacity:0;transition:opacity 0.2s;pointer-events:none}\n');
w('.diff-modal-overlay.active{opacity:1;pointer-events:auto}\n');
w('.diff-modal{background:var(--bg-card);border:1px solid var(--border);border-radius:12px;width:95%;max-width:1400px;max-height:90vh;display:flex;flex-direction:column;box-shadow:0 20px 60px rgba(0,0,0,0.5);transform:translateY(20px);transition:transform 0.2s}\n');
w('.diff-modal-overlay.active .diff-modal{transform:translateY(0)}\n');
w('.diff-modal-header{display:flex;align-items:center;justify-content:space-between;padding:14px 20px;border-bottom:1px solid var(--border)}\n');
w('.diff-modal-title{font-size:14px;font-weight:600;color:var(--text)}.diff-modal-close{width:30px;height:30px;border:none;background:var(--border);border-radius:6px;cursor:pointer;font-size:18px;color:var(--text-dim);display:flex;align-items:center;justify-content:center;transition:all 0.15s}.diff-modal-close:hover{background:var(--bg-card-hover);color:var(--text)}\n');
w('.diff-modal-body{flex:1;overflow:auto;padding:20px}.diff-loading{padding:40px;text-align:center;color:var(--text-muted);font-size:14px}.diff-empty{padding:40px;text-align:center;color:var(--text-muted);font-size:14px}\n');
w('.diff-plain-text{padding:16px;background:var(--bg);border:1px solid var(--border);border-radius:8px;font-family:\'SFMono-Regular\',Consolas,monospace;font-size:13px;line-height:1.7}\n');
w('.diff-plain-line{padding:2px 0;color:var(--text-dim);border-bottom:1px solid rgba(51,65,85,0.3)}.diff-plain-line:last-child{border-bottom:none}\n');
w('.diff-plain-comment{padding:4px 0;color:var(--yellow);font-weight:600;border-bottom:1px solid rgba(251,191,36,0.2);background:var(--yellow-bg);margin:2px -16px;padding-left:16px;padding-right:16px}\n');
w('.diff-file-card{background:var(--bg);border:1px solid var(--border);border-radius:10px;margin-bottom:16px;overflow:hidden}\n');
w('.diff-description{padding:12px 16px;background:var(--yellow-bg);border-bottom:1px solid rgba(251,191,36,0.2)}.diff-description-line{font-size:13px;color:var(--yellow);line-height:1.7}.diff-description-line:first-child{font-weight:600}\n');
w('.diff-file-header{padding:12px 16px;border-bottom:1px solid var(--border);background:var(--bg-card)}.diff-file-name{font-family:\'SFMono-Regular\',Consolas,monospace;font-size:13px;color:var(--accent);font-weight:600}.diff-file-desc{font-size:12px;color:var(--text-muted);margin-top:4px}\n');
w('.diff-hunks{display:flex;flex-direction:column}.diff-hunk-header{padding:6px 16px;font-size:11px;color:var(--text-muted);background:rgba(51,65,85,0.3);border-bottom:1px solid var(--border);font-family:\'SFMono-Regular\',Consolas,monospace}\n');
w('.diff-pair{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid var(--border)}.diff-pair-header{grid-column:1 / -1;display:grid;grid-template-columns:1fr 1fr}\n');
w('.diff-pair-header-left{padding:6px 12px;font-size:11px;font-weight:600;background:var(--red-bg);color:var(--red);border-bottom:1px solid rgba(248,113,113,0.2);border-right:1px solid var(--border)}\n');
w('.diff-pair-header-right{padding:6px 12px;font-size:11px;font-weight:600;background:var(--green-bg);color:var(--green);border-bottom:1px solid rgba(74,222,128,0.2)}\n');
w('.diff-side{font-family:\'SFMono-Regular\',Consolas,monospace;font-size:13px;line-height:1.6;overflow-x:auto}.diff-side-left{border-right:1px solid var(--border)}\n');
w('.diff-line-row{display:flex;white-space:pre}.diff-line-num{width:40px;min-width:40px;text-align:right;padding:2px 6px;font-size:11px;user-select:none;border-right:1px solid var(--border)}.diff-line-content{padding:2px 8px;flex:1}\n');
w('.diff-line-row.del{background:var(--red-bg)}.diff-line-row.del .diff-line-num{background:rgba(248,113,113,0.15);color:var(--red)}.diff-line-row.del .diff-line-content{color:var(--red)}\n');
w('.diff-line-row.add{background:var(--green-bg)}.diff-line-row.add .diff-line-num{background:rgba(74,222,128,0.15);color:var(--green)}.diff-line-row.add .diff-line-content{color:var(--green)}\n');
w('.diff-line-row.ctx{background:rgba(51,65,85,0.15)}.diff-line-row.ctx .diff-line-num{background:rgba(51,65,85,0.2);color:var(--text-muted)}.diff-line-row.ctx .diff-line-content{color:var(--text-dim)}\n');
w('.diff-line-row.empty{background:var(--bg)}.diff-line-row.empty .diff-line-num{background:var(--bg);color:var(--border)}.diff-line-row.empty .diff-line-content{color:var(--border)}\n');
w('@media(max-width:768px){.sidebar{width:180px}.main{padding:16px}.stats-grid{grid-template-columns:repeat(2,1fr)}.diff-modal{width:96%;max-height:90vh}.diff-pair{grid-template-columns:1fr}.diff-side-left{border-right:none;border-bottom:1px solid var(--border)}.module-card-header .mc-desc{display:none}}\n');
w('@media(max-width:600px){.sidebar{display:none}.main{padding:12px}.header{padding:16px}.stats-grid{grid-template-columns:1fr 1fr;gap:8px}.module-card-header{flex-wrap:wrap}.module-card-header .mc-bar{width:80px}}\n');
w('</style>\n</head>\n<body>\n');
w('<div class="layout">\n  <div class="sidebar">\n    <div class="sidebar-top"><div class="sidebar-project"><div class="sidebar-pulse"></div><span>星寰海</span></div></div>\n');
w('    <div class="sidebar-section"><div class="sidebar-label">概览</div><div class="sidebar-item active" data-view="overview"><span class="icon">📊</span> 仪表盘</div><div class="sidebar-item" data-view="modules"><span class="icon">📦</span> 模块看板</div></div>\n');
w('    <div class="sidebar-section"><div class="sidebar-label">历史记录</div><div class="sidebar-item" data-view="timeline"><span class="icon">🕐</span> 时间线</div><div class="sidebar-item" data-view="reviews"><span class="icon">🔍</span> 审查记录</div><div class="sidebar-item" data-view="tests"><span class="icon">🧪</span> 测试记录</div><div class="sidebar-item" data-view="decisions"><span class="icon">💡</span> 决策记录</div></div>\n');
w('    <div class="sidebar-section" id="date-index"><div class="sidebar-label">按日期查找</div></div>\n');
w('    <div class="sidebar-bottom"><div class="ws-status"><div class="ws-dot" id="ws-dot"></div><span id="ws-text">实时更新未连接</span></div></div>\n');
w('  </div>\n  <div class="main">\n    <div class="header" id="header-area"></div>\n');
w('    <div id="view-overview" class="view active"></div>\n    <div id="view-modules" class="view"></div>\n    <div id="view-timeline" class="view"></div>\n');
w('    <div id="view-reviews" class="view"></div>\n    <div id="view-tests" class="view"></div>\n    <div id="view-decisions" class="view"></div>\n  </div>\n</div>\n');
w('<div id="legacy-timeline" style="display:none"></div>\n');
w('<div id="diff-modal" class="diff-modal-overlay" onclick="closeDiffOnBackdrop(event)"><div class="diff-modal"><div class="diff-modal-header"><div class="diff-modal-title" id="diff-modal-title">改动详情</div><button class="diff-modal-close" onclick="closeDiff()">&times;</button></div><div class="diff-modal-body" id="diff-modal-body"><div class="diff-loading">加载中...</div></div></div></div>\n');
w('<script>\n');

ws.end(function() {
  console.log('Part 1 written successfully');
  console.log('Size:', fs.statSync(outPath).size);
});
