export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/pet-profile/index',
    'pages/timeline/index',
    'pages/family/index',
    'pages/mine/index',
  ],
  window: {
    navigationBarBackgroundColor: '#FFF6EE',
    navigationBarTextStyle: 'black',
    navigationBarTitleText: '星河宠记',
    backgroundColor: '#FFF6EE',
    backgroundTextStyle: 'light',
  },
  tabBar: {
    color: '#B69B83',
    selectedColor: '#FF6B3D',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/icons/home.png',
        selectedIconPath: 'assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/pet-profile/index',
        text: '宠物',
        iconPath: 'assets/icons/pet.png',
        selectedIconPath: 'assets/icons/pet-active.png',
      },
      {
        pagePath: 'pages/timeline/index',
        text: '时光',
        iconPath: 'assets/icons/timeline.png',
        selectedIconPath: 'assets/icons/timeline-active.png',
      },
      {
        pagePath: 'pages/family/index',
        text: '家庭',
        iconPath: 'assets/icons/family.png',
        selectedIconPath: 'assets/icons/family-active.png',
      },
      {
        pagePath: 'pages/mine/index',
        text: '我的',
        iconPath: 'assets/icons/mine.png',
        selectedIconPath: 'assets/icons/mine-active.png',
      },
    ],
  },
  subPackages: [
    {
      root: 'pagesPet',
      pages: [
        'add/index',
        'edit/index',
        'breed/index',
        'breed-detail/index',
        'checkin/index',
        'diary/index',
        'food-query/index',
        'symptom-check/index',
        'trends/index',
        'vaccine/index',
        'avatar-customize/index',
        'health-report/index',
        'grief/index',
        'hospital/index',
        'chronic-tracking/index',
        'feeding-advice/index',
        'naming/index',
        'family/dashboard/index',
        'family/calendar/index',
        'family/lineage/index',
        'memoir-daily/index',
        'memoir-vlog/index',
        'family/feed/index',
        'share-card/index',
        'leaderboard/index',
        'weekly-report/index',
        'yearly-review/index',
        'family-tree/index',
        'achievement/index',
      ],
    },
    {
      root: 'pagesUser',
      pages: [
        'profile/index',
        'settings/index',
        'onboarding/index',
        'agreement/index',
        'invite/index',
        'effect-tracking/index',
        'memory/index',
        'feedback/index',
        // 主包瘦身：登录页/会员中心页原在主包，迁入分包后主包体积降至 1.5M 以下（微信上传代码质量要求）
        'member/index',
        'login/index',
        // 登录后引导绑定微信头像昵称页（chooseAvatar + nickname 官方能力）
        'bind-wechat/index',
      ],
    },
  ],
  // 开启"组件按需注入"：微信代码质量检查要求主包启用 lazyCodeLoading，
  // 否则上传时该项"未通过"。开启后页面组件按需加载，也能顺带减小首包体积。
  lazyCodeLoading: 'requiredComponents',
  __usePrivacyCheck__: true,
})
