export { AvatarManager } from './AvatarManager'
export { AvatarRenderer, AvatarFallback, AvatarAnimationController } from './AvatarRenderer'
export { AvatarEvolutionPanel } from './AvatarEvolutionPanel'
export { avatarService } from './avatarService'
export { avatarStore } from './avatarStore'
export { avatarAIProvider, rpmProvider } from './avatarAIProvider'
export { checkEvolutionRules, applyEvolutionRewards, updateEvolutionStats, getEvolutionProgress } from './evolutionEngine'
export type { AvatarService } from './avatarService'
export type { IAvatarAIProvider, IRPMProvider } from './avatarAIProvider'
export type { AvatarDefinition, AvatarGenerationRequest, AvatarEvolution, AvatarRenderMode, AvatarStyle } from './avatarTypes'
